spring:
  application:
    name: board-api-service
  profiles:
    active: prod

server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force: true
      force-response: true

logging:
  level:
    com.phcworld: debug
    org.springframework.security: debug
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

kafka:
  broker:
    url: 127.0.0.1:9092
user_service:
  url: http://localhost:8080/users
answer_service:
  url: http://localhost:8082/answers
jwt:
  secret: spring-boot-security-test-secret-key-dev